version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-Linux
    command: npm run start:prod
    environment:
      APP_ENV: docker
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    volumes:
      - .:/app
    depends_on:
      - db
