version: '3'
services:
  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_CONNECTION_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_CONNECTION_PASSWORD}
    image: mongo:4.4.1-bionic
    ports:
      - 29056:27017

  redis:
    image: redis:6.2.1-alpine
    ports:
      - '6379:6379'
