export interface DbDotEnvVariables {
  MONGO_CONNECTION_AUTH_SOURCE: string;
  MONGO_CONNECTION_DB: string;
  MONGO_CONNECTION_PASSWORD: string;
  MONGO_CONNECTION_PROTOCOL: string;
  MONGO_CONNECTION_URL: string;
  MONGO_CONNECTION_USER: string;
}
