name: ci
on: [push]
jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Compile source files
        run: npm run build

      - name: Setup local files
        run: npm run setup:local

      - name: Cache MongoDb image (Default)
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: whoan
          password: "${{ secrets.GITHUB_TOKEN }}"  # you don't need to manually set this secret. GitHub does it on your behalf
          registry: docker.pkg.github.com
          image_name: mongo
          image_tag: 4.4.1-bionic
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Cache NodeJS image (Default)
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: whoan
          password: "${{ secrets.GITHUB_TOKEN }}"  # you don't need to manually set this secret. GitHub does it on your behalf
          registry: docker.pkg.github.com
          image_name: node
          image_tag: 12.18.4-alpine
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Launch docker images (Default)
        run: npm run docker:up:ci
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Wait test server
        run: node ./dist/scripts/waitForApiServer.js
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Launch Tests (Default)
        run: npm t
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Launch Unit Tests (Windows)
        run: npm run test:unit
        if: ${{ matrix.os == 'windows-latest' }}
